[package]
name = "generator"
version = "0.3.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT/ISC"
repository = "https://github.com/Xudong-Huang/generator-rs.git"
description = "Generator Library in Rust"
readme = "README.md"
homepage = "https://github.com/Xudong-Huang/generator-rs.git"
keywords = ["generator", "coroutine", "green", "thread", "fiber"]

[profile.release]
opt-level=3
