[package]
name = "generator"
version = "0.5.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "LGPL-2.1"
repository = "https://github.com/Xudong-Huang/generator-rs.git"
homepage = "https://github.com/Xudong-Huang/generator-rs.git"
documentation = "https://docs.rs/generator"
description = "Generator Library in Rust"
readme = "README.md"
keywords = ["generator", "coroutine", "green", "thread", "fiber"]
categories = ["data-structures", "algorithms"]
build = "build.rs"

[dependencies]
log = "0.3"

[build-dependencies]
rustc_version = "0.2"
gcc = "0.3"

[profile.release]
opt-level=3
